spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/simple-auth-db-v2
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  security:
#    user:
#      name: user
#      password: 12345
#      roles: USER